- hosts: all
  tasks:
    - name: Make sure timezone is set properly
      community.general.timezone:
        name: US/Eastern
      become: true
  roles:
    - role: patrickjahns.promtail
      vars: 
        promtail_config_include_default_file_sd_config: False
        promtail_config_clients:
          - url: "http://192.168.42.242:3100/loki/api/v1/push"
            external_labels:
              host: "{{ ansible_hostname }}"
        promtail_config_positions:
          filename: "{{ promtail_positions_directory }}/positions.yaml"
          sync_period: "60s"

        promtail_config_scrape_configs:
          - job_name: system
            static_configs:
            - targets:
                - localhost
              labels:
                job: varlogs
                __path__: /var/log/*log
          - job_name: octoprint
            static_configs:
            - targets:
              - localhost
              labels:
                host: "{{ ansible_hostname }}"
                job: octoprint
                __path__: /home/pi/.octoprint/logs/*.log 