- hosts: all
  tasks: 
    - name: Install pip dependencies
      pip: 
        virtualenv: /home/pi/oprint
        name: "git+https://github.com/jneilliii/OctoPrint-BedLevelVisualizer.git@0.1.15#egg=Bed-Visualizer"