- hosts: all
  remote_user: pi
  tasks: 
    - name: Install pip dependencies
      pip: 
        virtualenv: /home/pi/Octoprint/venv/
        name: 
          - "git+https://github.com/tg44/OctoPrint-Prometheus-Exporter.git@0.1.6#egg=OctoPrint-Prometheus-Exporter"
      notify:
        - Restart OctoPrint
  handlers:
    - name: Restart OctoPrint        ## Would be nice to have this check that a print isn't running before excuting
      become: true
      ansible.builtin.service:
        name: octoprint
        state: restarted