roles:
  - name: semuadmin.octoprint
    version: 1.0.2
  - name: patrickjahns.promtail
    version: 1.9.1
  - name: cloudalchemy.grafana
    version: 0.17.0
  - name: cloudalchemy.prometheus
    version: 2.16.2
  - name: geerlingguy.nodejs
    version: 5.1.1

collections:
