## Common Setups for all hosts
- hosts: all
  user: pi
  roles:
    - common
    - rpi_exporter
    - node_exporter

## Monitoring Server
- hosts: tpi1 
  user: pi
  roles:
    - monitoring_server 

## Octoprint Hosts
- hosts: tpi1 
  vars: 
    - install_mjpg_streamer: false
    - reset_config: false
    - octoprint_url: "https://github.com/OctoPrint/OctoPrint/archive/1.5.2.zip"
  become: yes
  user: pi
  roles: 
    - semuadmin.octoprint
    - octoprint_plugins

- hosts: monitoring_server
  user: pi
  roles:
    - role: cloudalchemy.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: admin
        grafana_datasources:
          - name: prometheus
            type: prometheus
            url: "http://{{ hostvars[inventory_hostname]['ansible_facts']['eth0']['ipv4']['address'] }}:9090"
            basicAuth: false
        grafana_dashboards:
          - dashboard_id: 1860    #Node Exporter Full Dashboard
            revision_id: 21
            datasource: prometheus