## Common Setups for all hosts
- hosts: all
  user: pi
  roles:
   - common
   - rpi_exporter
   - node_exporter

## Log all hosts syslog to Loki
- hosts: all
  become: yes
  user: pi
  roles:
    - role: patrickjahns.promtail
      vars: 
        promtail_config_include_default_file_sd_config: False
        promtail_config_clients:
          - url: "http://192.168.42.242:3100/loki/api/v1/push"
            external_labels:
              host: "{{ ansible_hostname }}"
        promtail_config_positions:
          filename: "{{ promtail_positions_directory }}/positions.yaml"
          sync_period: "60s"

        promtail_config_scrape_configs:
          - job_name: system
            static_configs:
            - targets:
                - localhost
              labels:
                job: varlogs
                __path__: /var/log/*log
          - job_name: octoprint
            static_configs:
            - targets:
              - localhost
              labels:
                host: "{{ ansible_hostname }}"
                job: octoprint
                __path__: /home/pi/.octoprint/logs/*.log

## Octoprint Hosts
- hosts: octoprint
  vars: 
    - install_mjpg_streamer: false
    - reset_config: false
    - octoprint_url: "https://github.com/OctoPrint/OctoPrint/archive/1.5.2.zip"
  become: yes
  user: pi
  roles: 
   - semuadmin.octoprint
   - octoprint_plugins

- hosts: monitoring_server
  user: pi
  roles:
    - role: monitoring_server
    # - role: cloudalchemy.prometheus
    #   vars:
    #     prometheus_scrape_configs:
    #       - job_name: "prometheus"
    #         metrics_path: "/metrics"
    #         static_configs:
    #         - targets:
    #           - "{{ ansible_host }}:9090"
    #       - job_name: "system"
    #         metrics_path: "/metrics"
    #         static_configs:
    #         - targets:
    #           - "{{ ansible_host }}:9100"  ## This needs to be a list of all hosts, not just the current one
    #       - job_name: "octoprint"   #This needs to be a loop of all printers
    #         metrics_path: "/plugin/prometheus_exporter/metrics"
    #         params:
    #           apikey: ['2F5AB5B30C22485FA75F87A8421C1D3A']  #Do we use a static API key for now, or try to pull the generated ones?
    #         static_configs:
    #         - targets:  #This needs to be a loop of all printers
              # - "{{ ansible_host }}:5000"
    - role: cloudalchemy.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: admin
        grafana_datasources:
          - name: prometheus
            type: prometheus
            url: "http://{{ hostvars[inventory_hostname]['ansible_facts']['eth0']['ipv4']['address'] }}:9090"
            basicAuth: false
        grafana_dashboards:
          - dashboard_id: 1860    #Node Exporter Full Dashboard
            revision_id: 21
            datasource: prometheus

- hosts: octofarm_server
  user: pi
  tasks:
  - name: Install a list of packages
    become: yes
    apt:
      update_cache: yes
      pkg:
      - nodejs
      - npm
      - gcc 
      - g++
      - make
     # - mongodb
  - name: Git checkout
    git:
      repo: 'https://github.com/NotExpectedYet/OctoFarm.git'
      dest: /home/pi/OctoFarm
  - name: Install Node Modules
    args:
      chdir: /home/pi/OctoFarm/
    command: npm install
  - name: Install pm2
    args:
      chdir: /home/pi/OctoFarm/
    command: npm install pm2 -g
    become: yes
  - name: Generate pm2 startupls
    command: pm2 startup
    args:
      chdir: /home/pi/OctoFarm/
  - name: Save pm2 setup
    command: pm2 save
    args:
      chdir: /home/pi/OctoFarm/