---
- hosts: all
  user: pi
  roles:
    - common
    - rpi_exporter
    - node_exporter

- hosts: tpi1 
  user: pi
  roles:
    - monitoring_server 

- hosts: tpi1 
  vars: 
    - install_mjpg_streamer: false
    - reset_config: false
    - octoprint_url: "https://github.com/OctoPrint/OctoPrint/archive/1.5.2.zip"
  become: yes
  user: pi
  roles: 
    - semuadmin.octoprint