---
# tasks file for octoprint

- name: Install python dependencies.
  package:
    name:
      - python3-pip
      - python-dev
      - python-setuptools
    state: present

- name: Install virtualenv via pip.
  pip:
    name:
      - virtualenv
    state: present

- name: Install other dependencies.
  package:
    name:
      - git
      - libyaml-dev
      - build-essential
    state: present

- name: Add octoprint user to tty and dialout groups.
  user:
    name: "{{ octoprint_user }}"
    groups: tty, dialout, video
    append: true

- name: Create octoprint directory.
  file:
    path: "{{ install_dir }}/Octoprint"
    state: directory
    owner: "{{ octoprint_user }}"
    group: "{{ octoprint_user }}"

- name: Create user config directory.
  file:
    path: "{{ install_dir }}/.octoprint/"
    state: directory
    owner: "{{ octoprint_user }}"
    group: "{{ octoprint_user }}"

- name: Install octoprint via pip.
  pip:
    name: "{{ octoprint_url }}"
    virtualenv: "{{ install_dir }}/Octoprint/venv"
    virtualenv_command: virtualenv
    state: present

- name: Install config.yaml template.
  template:
    src: config.yaml.j2
    dest: "{{ install_dir }}/.octoprint/config.yaml"
    owner: "{{ octoprint_user }}"
  when: reset_config
    
- name: Install init template.
  template:
    src: octoprint.init.j2
    dest: /etc/init.d/octoprint
    mode: +x
    owner: "{{ octoprint_user }}"

- name: Install default template.
  template:
    src: octoprint.default.j2
    dest: /etc/default/octoprint
    owner: "{{ octoprint_user }}"

- name: Install systemd service template.
  template:
    src: octoprint.service.j2
    dest: /etc/systemd/system/octoprint.service
    owner: "{{ octoprint_user }}"

- name: Change ownership of .octoprint directory
  file:
    path: "{{ install_dir }}/.octoprint"
    state: directory
    recurse: true
    owner: "{{ octoprint_user }}"
    group: "{{ octoprint_user }}"

- name: Change ownership of Octoprint directory
  file:
    path: "{{ install_dir }}/Octoprint"
    state: directory
    recurse: true
    owner: "{{ octoprint_user }}"
    group: "{{ octoprint_user }}"

- name: Start octoprint service.
  systemd:
    name: octoprint
    enabled: true
    state: restarted
    daemon_reload: true
