---
  - name: Install pip dependencies
    remote_user: pi
    pip: 
      virtualenv: /home/pi/Octoprint/venv/
      name: 
        - "git+https://github.com/tg44/OctoPrint-Prometheus-Exporter.git@0.1.6#egg=OctoPrint-Prometheus-Exporter"
    notify:
      - Restart OctoPrint