{
 "title": "PiCluster",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Raspberry Pi Temperatures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rpi_cpu_temperature_celsius" }
   ]
  },
  {
   "title": "whitepi eth0 status",
   "type": "vonage-status-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "eth0",
     "crit": 100,
     "disabledValue": "0",
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "node_network_up{device=\"eth0\", job=\"whitepi\"} OR on() vector(100)",
     "legendFormat": "eth0",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 50
    }
   ]
  },
  {
   "title": "bluepi eth0 status",
   "type": "vonage-status-panel",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "eth0",
     "crit": 100,
     "disabledValue": "0",
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "node_network_up{device=\"eth0\", job=\"bluepi\"} OR on() vector(100)",
     "legendFormat": "eth0",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 50
    }
   ]
  },
  {
   "title": "WhitePi RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "(((node_memory_MemTotal_bytes{job=\"whitepi\"} - node_memory_MemFree_bytes{job=\"whitepi\"} - node_memory_Buffers_bytes{job=\"whitepi\"} - node_memory_Cached_bytes{job=\"whitepi\"}) / node_memory_MemTotal_bytes{job=\"whitepi\"}) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "BluePi RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "(((node_memory_MemTotal_bytes{job=\"bluepi\"} - node_memory_MemFree_bytes{job=\"bluepi\"} - node_memory_Buffers_bytes{job=\"bluepi\"} - node_memory_Cached_bytes{job=\"bluepi\"}) / node_memory_MemTotal_bytes{job=\"bluepi\"}) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "whitepi CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"whitepi\", mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "bluepi CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"bluepi\", mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "redpi eth0 status",
   "type": "vonage-status-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "eth0",
     "crit": 100,
     "disabledValue": "0",
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "node_network_up{device=\"eth0\", job=\"redpi\"} OR on() vector(100)",
     "legendFormat": "eth0",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 50
    }
   ]
  },
  {
   "title": "greenpi eth0 status",
   "type": "vonage-status-panel",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "eth0",
     "crit": 100,
     "disabledValue": "0",
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "node_network_up{device=\"eth0\", job=\"greenpi\"} OR on() vector(100)",
     "legendFormat": "eth0",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 50
    }
   ]
  },
  {
   "title": "RedPi RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "(((node_memory_MemTotal_bytes{job=\"redpi\"} - node_memory_MemFree_bytes{job=\"redpi\"} - node_memory_Buffers_bytes{job=\"redpi\"} - node_memory_Cached_bytes{job=\"redpi\"}) / node_memory_MemTotal_bytes{job=\"redpi\"}) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "GreenPi RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "(((node_memory_MemTotal_bytes{job=\"greenpi\"} - node_memory_MemFree_bytes{job=\"greenpi\"} - node_memory_Buffers_bytes{job=\"greenpi\"} - node_memory_Cached_bytes{job=\"greenpi\"}) / node_memory_MemTotal_bytes{job=\"greenpi\"}) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "redpi CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"redpi\", mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "greenpi CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"greenpi\", mode=\"idle\"}[5m])) * 100)"
    }
   ]
  }
 ]
}